networks:
  toubeelib.net:
    driver: bridge

services:

  # service api.toubeelib : api pour la prise de rdv
  #
  api.toubeelib:
    build:
      context: build
      dockerfile: Dockerfile_Principal
    env_file: ./toubeelib.env
    ports:
      - 6080:80
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public


  # service api.praticien : api pour la partie praticien de toubeelib
  #
  api.praticien:
    build:
      context: build
      dockerfile: Dockerfile_Principal
    env_file: ./toubeelib.env
    ports:
      - 2080:80
    volumes:
      - ./app-praticiens:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # service api.rdv : api pour la partie rdv de toubeelib
  #
  api.rdv:
    build:
      context: build
      dockerfile: Dockerfile_Principal
    env_file: ./toubeelib.env
    ports:
      - 3080:80
    volumes:
      - ./app-rdv:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # service api.rdv : api pour la partie rdv de toubeelib
  #
  api.securite:
    build:
      context: build
      dockerfile: Dockerfile_Principal
    env_file: ./toubeelib.env
    ports:
      - 4080:80
    volumes:
      - ./app-secu:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # gateway.toubeelib : api gateway pour toubeelib
  #
  gateway.toubeelib:
    build:
      context: build
      dockerfile: Dockerfile_Gateway
    ports:
      - 1000:8080
    networks:
      - toubeelib.net
    volumes:
      - ./apiGateway:/var/php
    working_dir: /var/php
    depends_on:
      - api.toubeelib
    command: php -S 0.0.0.0:8080 -t /var/php/public

  # service toubeelib.db : base de données postgresql
  toubeelib.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    ports:
      - 5432:5432
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - toubeelib.net
    
    

